[project]
name = "thumb-drive-auto-copy"
version = "0.1.0"
description = "Auto copy files from removable media"
authors = [
    {name = "Maker By Night",email = "2565361+mshafer1@users.noreply.github.com"}
]
license = "MIT"
requires-python = ">=3.11,<4"
dynamic = ["dependencies"]
packages = [
    {include = "thumb_drive_auto_copy", from = "src"}
]
scripts = {thumb-drive-auto-copy = "thumb_drive_auto_copy.__main__:main"}

[tool.poetry.dependencies]
click = "^8.4.2"
pyqt6 = "^6.11.0"
qasync = "^0.28.0"
pyyaml = "^6.0.3"
filelock = "^3.29.4"
python-decouple = "^3.8"

[tool.poetry.group.installer.dependencies]
pyinstaller = {version = "^6.21.0", python="^3.11,<3.16"}

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
ni-python-styleguide = "^0.5.0"
pytest = "^9.1.1"
poethepoet = "^0.47.1"

[tool.poe.tasks]
format = "ni-python-styleguide format"
lint = "ni-python-styleguide lint"
build = "pyinstaller --clean --noconfirm --onefile --noconsole --name thumb-drive-auto-copy src/thumb_drive_auto_copy/__main__.py"
all = ["format", "lint", "build"]
